# Generated by Django 5.1.1 on 2024-09-20 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.position",
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="project",
            field=models.ManyToManyField(blank=True, null=True, to="catalog.project"),
        ),
    ]
