# Generated by Django 5.1.1 on 2024-09-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_worker_position_alter_worker_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="project",
            field=models.ManyToManyField(to="catalog.project"),
        ),
    ]
