# Generated by Django 5.1.1 on 2024-09-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_task_assignees"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["priority"]},
        ),
    ]
