# Generated by Django 5.1.1 on 2024-09-20 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_task_options_project_positions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="positions",
        ),
        migrations.RemoveField(
            model_name="project",
            name="task_types",
        ),
    ]
