# Generated by Django 5.1.1 on 2024-09-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_remove_project_positions_remove_project_task_types"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="worker",
            managers=[],
        ),
        migrations.AddField(
            model_name="worker",
            name="email_is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="worker",
            name="email",
            field=models.EmailField(
                max_length=50, unique=True, verbose_name="Email Address"
            ),
        ),
    ]
